### ISSUE TITLE
handle blank lines properly

### ISSUE THREAD

**Issue by aspiers** [adrianomitre/heredoc_unindent#1]
Firstly, thanks for your work on this gem.

I know this is already covered in the Wishlist, but I just wasted 20 minutes trying to find out why this gem wasn't working for me, before discovering that it can't handle blank lines.  Blank lines in heredocs is an extremely common use case, so it's a fairly major deficiency for such a simple gem - if you can't fix it soon, please at least document it prominently on the front page so that other people don't waste time like I just did.  Thanks!

**Comment by adrianomitre** [comment]
Thanks for pointing out. You are welcome to contribute with an improvement/fix, possibly based on the Wishlist suggestion. I will not hesitate to accept your pull.

**Comment by adrianomitre** [comment]
The wish came true. Enjoy!
